<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="P29.css"?> 
<!DOCTYPE bookstore[
<!ELEMENT bookstore (book+)>
<!ELEMENT book (name,author,price)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<bookstore>
<book>
    <name>Introduction to C Programming</name>
    <author>Yashwant Kanekar</author>
    <price>350</price>
</book>
<book>
    <name>Introduction to Javascript</name>
    <author>Sujal Kumar</author>
    <price>500</price>
</book>
<book>
    <name>Introduction to Black Hat Hacking</name>
    <author>Sujal Kumar</author>
    <price>1000</price>
</book>
</bookstore>